SMTP_ADDRESS: 'smtp.gmail.com'
SMTP_PORT: '587'
SMTP_DOMAIN: 'gmail.com'
SMTP_USER_NAME: 'username@change.me'
SMTP_PASSWORD: '<password>'
SMTP_AUTHENTICATION: 'plain'
SMTP_ENABLE_STARTTLS_AUTO: 'true'

APP_HOST: 'lvh.me'
APP_PROTOCOL: 'http'
EMAIL_ADDRESS: 'noreply@change.me'

SECRET_KEY_BASE: 'REPLACE with rake secret output'
NEW_RELIC_LICENSE_KEY: 'REPLACE with the one provided by NewRelic'

# Extra application options
ALLOW_CONCLUSION_FINAL_REVIEW_DESTRUCTION: 'true'
ALLOW_FINDING_ASSUMED_RISK_TO_PENDING: 'true'
ALLOW_REVIEW_CONTROL_OBJECTIVE_DUPLICATION: 'true'
AUTOMATICALLY_SORT_FINDINGS_ON_CONCLUSION: '{}' # In JSON
DEFAULT_LDAP_ROLES: ''
DISABLE_COI_AUDIT_DATE_VALIDATION: 'true'
DISABLE_FINDING_FINAL_STATE_ROLE_VALIDATION: 'true'
DISABLE_FINDINGS_EXPIRATION_NOTIFICATION: 'true'
DISABLE_REVIEW_AUDITED_VALIDATION: 'true'
HIDE_BUSINESS_UNIT_SCORES: 'true'
HIDE_CONTROL_COMPLIANCE_TESTS: 'true'
HIDE_CONTROL_EFFECTS: 'true'
HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS: 'true'
HIDE_CONTROL_OBJECTIVE_RISK: 'true'
HIDE_FINDING_CRITERIA_MISMATCH: 'true'
HIDE_OPORTUNITIES: 'true'
HIDE_REVIEW_DESCRIPTION: 'true'
HIDE_WEAKNESS_EFFECT: 'true'
HIDE_WEAKNESS_PRIORITY: 'true'
ORDER_REVIEWS_BY: 'conclusion_final_review'
ORDER_WEAKNESSES_ON_CONCLUSION_REVIEWS_BY: 'control_objective_items'
ORGANIZATIONS_WITH_BEST_PRACTICE_COMMENTS: 'cirope'
ORGANIZATIONS_WITH_CONTROL_OBJECTIVE_COUNTS: 'cirope'
ORGANIZATIONS_WITH_REVIEW_SCORE_BY_WEAKNESS: ''
PLAN_ITEM_REVIEW_CONCLUDED_ON: 'issue_date'
SCORE_BY_WEAKNESS: '{}' # In JSON
SHOW_ALTERNATIVE_QUESTIONNAIRES: 'true'
SHOW_ASSUMED_RISK_AS_REVIEW_PENDING: 'true'
SHOW_CONCLUSION_ALTERNATIVE_PDF: '{"cirope": "gal"}'
SHOW_CONCLUSION_AS_OPTIONS: 'true'
SHOW_EXTENDED_RISKS: 'true'
SHOW_FINDING_CURRENT_SITUATION: 'true'
SHOW_ORGANIZATION_PREFIX_ON_REVIEW_NOTIFICATION: 'cirope'
SHOW_REVIEW_AUTOMATIC_IDENTIFICATION: 'true'
SHOW_REVIEW_BEST_PRACTICE_COMMENTS: 'true'
SHOW_REVIEW_EXTRA_ATTRIBUTES: 'true'
SHOW_SHORT_QUALIFICATIONS: 'true'
SHOW_WEAKNESS_EXTRA_ATTRIBUTES: 'true'
SHOW_WEAKNESS_PROGRESS: 'true'
USE_SHORT_RELEVANCE: 'true'
WEAKNESS_SCORE_OBSOLESCENCE: ''
WEAKNESS_TAG_VALIDATION_START: '2016-08-08'
WEAKNESS_WEIGHTS: '{}' # In JSON

production:
  APP_PROTOCOL: 'https'
